language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update
  - sudo apt-get install coreutils  # Install coreutils for chmod command

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot

script:
  - travis_wait 60 bash -c "while true; do echo 'Build in progress...'; sleep 60; done & \
    sudo chmod +x * && sudo chmod +x suhani && python3 suhani.py"
