version: 1.0.{build}

# Specify the platform and Python version
image: Ubuntu

environment:
  matrix:
    - PYTHON: "3.10"

# Install Python and dependencies
install:
  - sudo apt-get update
  - sudo apt-get install python3.10 python3.10-venv python3.10-dev -y
  - python3.10 -m ensurepip --upgrade
  - python3.10 -m pip install --upgrade pip
  - python3.10 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot

# Run the script
build_script:
  - chmod +x *
  - python3.10 suhani.py  # Replace 'suhani.py' with your script name

# Branch trigger
branches:
  only:
    - main
