version: 1.0.{build}

# Use Ubuntu environment
image: Ubuntu

# Install dependencies
install:
  - sudo apt-get update
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot

# Build and run the script
build_script:
  - chmod +x *
  - python3 suhani.py  # Replace 'suhani.py' with your script name

# Branch specification
branches:
  only:
    - main  # Run pipeline only for 'main' branch
