version: 1.0.{build}

# Ubuntu 22.04 इमेज का उपयोग करें, जिसमें Python 3.10 प्री-इंस्टॉल्ड है
image: Ubuntu2204

# पर्यावरण चर सेट करें
environment:
  PYTHON: "3.10"

# निर्भरताएँ स्थापित करें
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot

# स्क्रिप्ट चलाएँ
build_script:
  - chmod +x suhani.py  # सुनिश्चित करें कि स्क्रिप्ट निष्पादन योग्य है
  - python3 suhani.py   # अपनी स्क्रिप्ट का नाम यहाँ उपयोग करें

# केवल मुख्य शाखा पर निर्माण ट्रिगर करें
branches:
  only:
    - main
