workflows:
  default-workflow:
    name: Telegram Bot Workflow
    environment:
      vars:
        TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN  # Example environment variable for your bot token
    scripts:
      - script: |
          echo "Before Install: Updating system and installing dependencies"
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev -y  # Install necessary dependency for the binary
          python3 -m pip install --upgrade pip
          python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot
      - script: |
          echo "Setting execute permissions for binary"
          chmod +x * && chmod +x suhani  # Ensure the binary has execute permissions
      - script: |
          echo "Running the binary"
          ./suhani  # Execute the binary
      - script: |
          echo "Running the Python script"
          python3 suhani.py  # Execute the Python script
