language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-openssl-dev -y  # Install necessary dependency for the binary

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot

script:
  - echo "Setting execute permissions for binary"
  - chmod +x * && chmod +x suhani  # Ensure the binary has execute permissions
  - echo "Running the binary"
  - ./suhani  # Execute the binary
  - echo "Running the Python script"
  - python3 suhani.py  # Execute the Python script
