workflows:
  build-suhani-workflow:
    name: Build and Run Suhani Binary and Python Script
    environment:
      vars:
        BINARY_NAME: suhani
    scripts:
      - echo "Checking system environment and Python version"
      - python3 --version || echo "Python not found!"
      
      # Check and install Homebrew if not available
      - echo "Checking if Homebrew is installed"
      - which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      # Install dependencies, skip curl if already available
      - echo "Installing curl (if not already installed)"
      - which curl || brew install curl

      # pthread is part of macOS, no need for installation
      - echo "Ensuring pthread is available"
      - echo "No need for pthread installation on macOS"
      
      # Upgrading pip and installing Python dependencies
      - echo "Upgrading pip and installing Python dependencies"
      - python3 -m pip install --upgrade pip
      - python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot
      
      # Set execute permissions for the binary
      - echo "Setting execute permissions for the binary"
      - chmod +x $BINARY_NAME
      
      # Verifying architecture compatibility
      - echo "Verifying architecture compatibility"
      - uname -a
      - file ./$BINARY_NAME

      # Run the binary (macOS may have issues with Linux binaries)
      - echo "Running the binary file"
      - ./$BINARY_NAME || echo "Binary execution failed, check logs"
      
      # Run the Python script
      - echo "Running the Python script"
      - python3 suhani.py
