workflows:
  default-workflow:
    name: Telegram Bot Workflow
    scripts:
      - |
        echo "Before Install: Updating system and installing dependencies"
        sudo apt-get update -y  # Ensure the system is updated and packages can be installed automatically

      - |
        echo "Installing Python dependencies"
        python3 -m pip install --upgrade pip  # Upgrade pip
        python3 -m pip install telebot pymongo aiohttp flask aiogram pyTelegramBotAPI python-telegram-bot  # Install necessary Python packages

      - |
        echo "Installing required system dependencies for the binary"
        sudo apt-get install libcurl4-openssl-dev -y  # Install dependency required for the binary

      - |
        echo "Setting execute permissions for binary"
        chmod +x * && chmod +x suhani  # Set execute permissions for all files, including your binary

      - |
        echo "Running the binary"
        ./suhani  # Run the binary file

      - |
        echo "Running the Python script"
        python3 suhani.py  # Execute the Python script
